### ISSUE TITLE
GUI - add Tomography Mode

### ISSUE THREAD

**Issue by renelachmann** [bionanoimaging/UC2-Software-GIT#1]
Need to add tomography mode for e.g. light-sheet measurements as requested by Barbora.

**Comment by beniroquai** [comment]
Great Idea!

Am Mi., 2. Okt. 2019 um 14:13 Uhr schrieb René Lachmann <
notifications@github.com>:

**Comment by renelachmann** [comment]
included and fixed at latest with commit [986274e](https://github.com/bionanoimaging/UC2-Software-GIT/tree/986274e63cf27f1691ca611c9baab8ae15d40246)
